# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tales from the nth floor
email: dccitaliano __at__ gmail __dot__ com
description: > # this means to ignore newlines until "baseurl:"
  Compilers, programming languages, math and other random
  areas of interest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dcci.github.io" # the base hostname & protocol for your site
github_username:  dcci

# Build settings
markdown: kramdown
